### ISSUE TITLE
ro-crate-metadata.json synchronization fails

### ISSUE THREAD

**Issue by beepsoft** [Arkisto-Platform/describo-online#57]
I am trying to use the latest version and both with the local and the onedrive configuration I get an error like this and `ro-crate-metadata.json` doesn't get synced to neither to the local directory nor to onedrive (the temp `ro-crate-metadata.json` exists and readable):

```
api_1   | 2022-09-29T12:35:53.217Z DEBUG: GET: /load/:service
api_1   | 2022-09-29T12:35:53.221Z DEBUG: POST: /profile
api_1   | 2022-09-29T12:35:53.264Z DEBUG: List folder: local /home/xxx/19
api_1   | 2022-09-29T12:35:53.355Z DEBUG: loading crate file @ /srv/tmp/b2303d0d-3ecc-4a96-ab04-977b7ad39109/current/ro-crate-metadata.json
api_1   | 2022-09-29T12:35:53.356Z DEBUG: Minting a new collection for this crate
api_1   | 2022-09-29T12:35:53.363Z DEBUG: Adding collection identifier to crate
api_1   | 2022-09-29T12:35:53.365Z DEBUG: Setting the collection id in the user session
api_1   | 2022-09-29T12:35:53.467Z ERROR: syncLocalFileToRemote: 2022/09/29 12:35:53 ERROR : : error listing: directory not found
api_1   | 2022/09/29 12:35:53 Failed to hashsum with 2 errors: last error was: directory not found
api_1   |
api_1   | Error: 2022/09/29 12:35:53 ERROR : : error listing: directory not found
api_1   | 2022/09/29 12:35:53 Failed to hashsum with 2 errors: last error was: directory not found
api_1   |
api_1   |     at ChildProcess.<anonymous> (file:///srv/api/src/lib/file-browser_rclone.js:234:20)
api_1   |     at ChildProcess.emit (events.js:400:28)
api_1   |     at maybeClose (internal/child_process.js:1088:16)
api_1   |     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
api_1   | 2022-09-29T12:35:53.469Z DEBUG: Loading the crate data into the database
api_1   | 2022-09-29T12:35:53.849Z DEBUG: GET: /entity/:entityId
api_1   | 2022-09-29T12:35:53.881Z DEBUG: POST: /definition
api_1   | 2022-09-29T12:35:53.929Z DEBUG: GET: /entity/:entityId/properties
```

My development-configuration.json is this:

```json
{
  "ui": {
    "siteName": "Arkisto Platform - Describo",
    "logo": "http://www.researchobject.org/ro-crate/assets/img/ro-crate.svg",
    "login": "localhost",
    "services": {
      "localhost":  true,
      "onedrive": {
        "clientId": "XXXXXXX",
        "tenantId": "XXXXXXX",
        "redirectUri": "http://localhost:9000/onedrive-callback"
      }
    },
    "maxSessionLifetime": "86400",
    "maxEntitiesPerTemplate": "100"
  },
  "api": {
    "port": 8080,
    "periodicProcessInterval": 300,
    "typeDefinitions": "https://raw.githubusercontent.com/Arkisto-Platform/arkisto-type-definitions/master/types/type-definitions.json",
    "typeDefinitionsLookup": "https://raw.githubusercontent.com/Arkisto-Platform/arkisto-type-definitions/master/types/type-definitions-lookup.json",
    "session": {
      "lifetime": {
        "hours": 5
      },
      "secret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    },
    "services": {},
    "applications": []
  }
}

```

**Comment by beepsoft** [comment]
The regression seems to be caused by commit 0a021fd3f0bf3e43678abe8dabb2b8445f9cb674

**Comment by marcolarosa** [comment]
I haven't seen this problem since committing 8637a8086e04d33f59c81ff7c9e68b56349583a1 but I've just totally removed that code (https://github.com/Arkisto-Platform/describo-online/commit/28c7dcda61b50465c1082666d0a6b3107a1822e5) so hopefully the issue is now gone.

**Comment by beepsoft** [comment]
Thanks, it works now!

**Comment by Heiss** [comment]
Thank you for your fix. We had the same issue.
